### ISSUE TITLE
字体会变大？

### ISSUE THREAD

**Issue by adolfheir** [KonghaYao/cn-font-split#1]
为啥用这个去拆思源雅黑的 ttf时候字体会显示的很大？ 

字体下载链接:  https://github.com/Pal3love/Source-Han-TrueType/releases/tag/2.004-2.001-1.002-R
![image](https://user-images.githubusercontent.com/26828649/236608167-14ca7f48-96bc-4f31-98d2-254880681f76.png)

eg：
![image](https://user-images.githubusercontent.com/26828649/236608210-2886c0a5-269c-4a6f-b8fa-c7d04f315a51.png)

**Comment by KonghaYao** [comment]
应该是设置字体大小不对，这个应该可以通过调节 font-size 解决

**Comment by adolfheir** [comment]
> 应该是设置字体大小不对，这个应该可以通过调节 font-size 解决

不是字体大小  设置的font-size没多大 但是显示的就特别大

**Comment by KonghaYao** [comment]
可能是原始字体的某些设定文件没有写到分包里面，测试中的其它字体没有这个问题，可能需要仔细修复一波

**Comment by adolfheir** [comment]
我猜应该也是一些头信息不对 主要对字体格式不太熟悉 所以麻烦你看下

**Comment by KonghaYao** [comment]
感谢您的反馈，3.0.5 版本尝试修复了这个BUG，我这边是成功了，但还是请您帮我测试一下啦😄 @adolfheir

**Comment by adolfheir** [comment]
可以了 感谢🙏
提个建议 第一层切可以让用户传 然后可以给这一层做preload  不过我准备改改你的代码自己搞 hhh

**Comment by KonghaYao** [comment]
如果您有什么不懂的，可以问 chatgpt，这个项目里面有挺多 字体的东西的，它给的建议很不错！

**Comment by adolfheir** [comment]
👌 感谢
