### ISSUE TITLE
中文字体 华文字体上传一直未反应

### ISSUE THREAD

**Issue by JackMyCode** [KonghaYao/cn-font-split#103]
[STKaitiSC.zip](https://github.com/user-attachments/files/17932130/STKaitiSC.zip)
![Snipaste_2024-11-27_17-36-18](https://github.com/user-attachments/assets/d2f22dda-575a-4c7c-9726-b128c765a3a2)
一直卡在这个，没有反应

**Comment by KonghaYao** [comment]
收到

**Comment by KonghaYao** [comment]
@JackMyCode 感谢您的反馈，这个问题是由于 cn-font-split 的依赖 workerpool 发生了变更，导致浏览器中的分包错误，我们已经发布新版本 6.0.2， 浏览器版本可能存在延迟和缓存，可刷新本地解决
