### ISSUE TITLE
Vite 插件在 Astro 框架中频繁出现缓存重建导致卡顿

### ISSUE THREAD

**Issue by SamuNatsu** [KonghaYao/cn-font-split#108]
如题，在 [Astro](https://astro.build) 中使用 `vite-plugin-font` 作为 Vite 插件，在开发服务器中每次热更新时都会看到插件在 log 中说删除了缓存，然后又重建了缓存，导致开发过程缓慢且卡顿

<img width="781" alt="image" src="https://github.com/user-attachments/assets/95577082-17fe-4e2b-aca7-b7ec43924ca5" />

如上图所示，红线以上是开发服务器启动时输出的信息，可以看见第一次插件预构建了字体分片  
红线以下是修改了一点内容触发了热更新后的情况，发现插件又重新执行的域构建，这导致热更新时间被大大拉长

**Comment by KonghaYao** [comment]
@SamuNatsu 你好，可以提供一下您的 astro.config 配置么

**Comment by SamuNatsu** [comment]
用的是 Astro v5

```ts
/// Astro config
import { defineConfig } from 'astro/config';
import path from 'node:path';

// Integrations
import d2 from 'astro-d2';
import icon from 'astro-icon';
import mdx from '@astrojs/mdx';
import pagefind from 'astro-pagefind';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';

// Remark plugins
import remarkExtendedTable from 'remark-extended-table';
import remarkMath from 'remark-math';
import remarkWordCount from './remark-plugins/word-count';

// Rehype plugins
import rehypeElementWrapper from './rehype-plugins/element-wrapper';
import rehypeExternalLinks from 'rehype-external-links';
import rehypeImageProcess from './rehype-plugins/image-process';
import rehypeKatex from 'rehype-katex';

// Vite plugins
import font from 'vite-plugin-font';

// Export config
export default defineConfig({
  integrations: [
    d2({ output: "imgs/d2" }),
    mdx(),
    icon(),
    tailwind({ nesting: true }),
    pagefind(),
    sitemap(),
  ],
  markdown: {
    remarkPlugins: [remarkExtendedTable, remarkMath, remarkWordCount],
    rehypePlugins: [
      [
        rehypeElementWrapper,
        { selector: 'table', wrapper: 'div.table-wrapper' }
      ],
      [
        rehypeExternalLinks,
        {
          protocols: ['http', 'https', 'mailto'],
          rel: ['noopener', 'noreferer'],
          target: '_blank'
        }
      ],
      rehypeImageProcess,
      [rehypeKatex, { output: 'html' }]
    ]
  },
  vite: {
    plugins: [font.vite()]
  }
});

```

**Comment by KonghaYao** [comment]
@SamuNatsu 
我检查了 4.0.0 版本 vite-plugin-font, 没有重现热更新问题
这个 pre-building 只有插件的 load 函数能够触发，所以很可能您的某个插件触发了全量的页面刷新，导致 vite-plugin-font 也重新加载了一遍
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/1b14d726-28a7-4979-9cd9-c901ca2a7f45" />

https://github.com/KonghaYao/cn-font-bundler-demo/tree/astro

**Comment by SamuNatsu** [comment]
找到了，`astro-icon` 集成的更新逻辑有问题，会导致热更新时用 `load` 刷新一遍

https://github.com/natemoo-re/astro-icon/issues/257#issue-2714560116

只能等上游更新了

**Comment by SamuNatsu** [comment]
所以可以的话能不能提供一个配置项，在 dev 模式下暂时不进行字体分片，而是直接提供全量字体，只有 build 模式下才进行分片

这样子也能节省开发服务器的冷启动时间

**Comment by KonghaYao** [comment]
@SamuNatsu 可以的，vite-plugin-font 每次 dev 都会重新构建，这个对于本身全量构建的字体是没有必要的，而且上次的构建产物也一直都是能用的。只是当初的时候为了保持缓存一致性做的，由于 v6 版本 cn-font-split 的稳定性确实够好，这一方面仍有优化空间。
       最近我在着重实现 Rust 版本的封装，v7 性能会远远高于 v6, 现在快到最后一阶段, 这个需求会适当推迟哈。

**Comment by SamuNatsu** [comment]
感谢，希望在 v7 release 之后能够尽快支持这种特性吧

我重新开个 feature request 吧
