### ISSUE TITLE
`Cargo.lock` missing in repo

### ISSUE THREAD

**Issue by Cryolitia** [KonghaYao/cn-font-split#113]
The file `Cargo.lock` should be tracked in version control, otherwise it is hard to package the rust program in software packages sourcess. (As a background, I'm a maintainer of NixOS and a contributor of Arch Linux Packages)

ref1: https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control
ref2: https://github.com/NixOS/nixpkgs/blob/4fc53b59aecbc25c0e173163d60155f8fca14bfd/doc/languages-frameworks/rust.section.md#compiling-rust-applications-with-cargo

**Comment by KonghaYao** [comment]
Thank you for pointing this out. We've updated the top-level .gitignore file to correctly include Cargo.lock. This ensures that it will be tracked in version control, facilitating more reliable packaging for distribution. Your insight is much appreciated.
