### ISSUE TITLE
discussion: improve the rust part

### ISSUE THREAD

**Issue by Cryolitia** [KonghaYao/cn-font-split#114]
### strip nodejs as build dependency

If you would like to get rid of the nodejs scripts to pre-process the data, I have written the crate `lang_unicodes` in rust. It uses opencc instead of `chinese-simple2traditional` but make the build environment more complex. I'm glad to open a PR about it if you like the idea.

Link: https://github.com/Cryolitia/yet-another-lang-unicodes-rs

### shell completion and manpage

We could use `clap_autocomplete` and `clap_mangen` to provide these, which have been already widely uses in other rust cli tools.

**Comment by KonghaYao** [comment]
@Cryolitia 
Regarding the first point, I agree that it is excellent. The lang_unicodes library has been migrated from JavaScript and hasn't undergone any modifications yet.

As for the second point, incorporating an autocomplete feature is indeed a great idea. Moving forward, the CLI functions of cn-font-split will adopt protobuf to directly generate definitions. There is already a preliminary form of this in packages/ffi-js/scripts/gen_cli_interface. By using protobuf, we can standardize most of the input parameter definitions, thereby reducing redundant work. At that time, I will also add support for autocomplete and manpage generation.
