### ISSUE TITLE
可以支持自定义分包文件名吗？

### ISSUE THREAD

**Issue by richex-cn** [KonghaYao/cn-font-split#16]
主要是考虑优化网络传输数据量。

当前是用 hash 字符串作为文件名，也许可以支持自定义使用自增数字、短 hash 等？

例如短 hash：

```
9c80b303.woff2
43c9a8cf.woff2
...
```

自增数字：

```
0.woff2
1.woff2
...
24.woff2
...
```

或 Base 36：

```
0.woff2
1.woff2
...
z.woff2
...
0z.woff2
...
zz.woff2
...
```

甚至将字母、数字以及一些对所有系统、浏览器都兼容的字符加入进来：

```
-.woff2
_.woff2
^.woff2
...
-z.woff2
_z.woff2
...
```

虽然是个小优化，但也能一定程度减少网络传输数据量。

以 40 个文件为例，当前 32 位 hash 需要 32*40=1280 字节，使用自增数字只有 72 字节。

主要涉及的地方为 `result.css` 中的 `url("***.woff2")` 字体文件路径，以及每个字体文件请求路径。

CSS 文件通过 gzip 压缩可以降低请求数据量，但 HTTP 请求字体文件时的路径包含字体文件名无法压缩。

参考类似 [Webpack 的 Template String](https://webpack.js.org/configuration/output/#template-strings)。

**Comment by KonghaYao** [comment]
我新建了一个分支实现了这个 feature，你可以通过配置 config 中的这个函数自定义字体的名称。这个feature的实现方式还可以修改，如果你有更好的实现方式的话，欢迎 PR。我们将会在您确认后发布到 beta 版本。

https://github.com/KonghaYao/cn-font-split/blob/59062063fcbba9412ff488ab44dca7e80897531c/packages/subsets/test/node.test.mjs#L23-L26

这样子实现是因为 hash 在多个平台适配上经过了特殊处理。如果需要自定义，向外暴露修改操作比较好。

关于文件命名的话，涉及到了 CDN 的缓存，中文网字计划有一个庞大的 CDN， 用于页面静态文件缓存。

我们经常使用它来作为 cn-font-split 实现效果的检测，这样就会有很多新旧版本的文件冲突问题。

一般我们不会使用自增的文件名称，因为那样需要更新的文件太多了，服务器需要 purge 很长时间。利用 hash 不冲突的特性可以实现只更新索引文件（result.css），然后浏览器自动下载新的分片。

diff 地址：
https://github.com/KonghaYao/cn-font-split/compare/ts...feature/renameOutputFile

**Comment by richex-cn** [comment]
[这里](https://github.com/KonghaYao/cn-font-split/blob/dcde9f8201d57a3f7fe0c63bb8f6116ce0b165d3/packages/subsets/src/useSubset/createRecord.ts#L15)默认使用 `[hash][ext]` 后，`filename` 始终有一个正确的值，使用 hash+ext 的 `path` 属性我在项目其他位置没找到有特别用途，是不是没必要增加一个 `filename` 属性，直接复制给 `path` 就行了？ @KonghaYao 

https://github.com/KonghaYao/cn-font-split/blob/dcde9f8201d57a3f7fe0c63bb8f6116ce0b165d3/packages/subsets/src/useSubset/createRecord.ts#L15

**Comment by richex-cn** [comment]
现在这样改动可以自行配置挺好的，可以向下兼容。

提了个 PR #17 ，参考 Webpack 支持了字符串模板，例如自增文件名只需要 `renameOutputFont: '[index][ext]'` 就行了。

另外对于使用自增文件名的缓存更新问题，通常生产环境中极少会更新已经完成分包的静态文件，如果确实需要更新并且使用了自增文件名，也可以通过新增的 `renameOutputFont` 配置项解决，按照字符串模板的方式可以手动在第二次分包时使用 `renameOutputFont: 'A[index][ext]'`，第三次 `'B[index][ext]'`，或者像这样自动的生成一个基于日期并且尽可能短的文件名：

```js
...
  renameOutputFont: (hash, ext, index) => {
    const pad2 = num => num.toString().padStart(2, '0')
    const now = new Date()
    const date = [
      now.getFullYear() % 2000,
      pad2(now.getMonth() + 1),
      pad2(now.getDate())
    ].join('')
    return Number(date).toString(36) + index.toString(36) + ext
  }
...
```

会得像这样的结果：

```
4y9a0.woff2
4y9a1.woff2
...
4y9az.woff2
...
```

当然这只是一个例子，还有很多方法，根据实际情况自由发挥。

**Comment by KonghaYao** [comment]
[4.9.0-beta.2](https://www.npmjs.com/package/@konghayao/cn-font-split/v/4.9.0-beta.2) 本周版本 beta 2 发布，已经将您的 feature 加入，如有想要的功能，欢迎 PR 或 Issues！😊
