### ISSUE TITLE
[feature request] 希望可以通过配置以显式移除生成 css 中的 font-weight 字段

### ISSUE THREAD

**Issue by immccn123** [KonghaYao/cn-font-split#31]
似乎没有办法取消默认的 css 的 font-weight 设置，这对 Variable Font 的不同字重比较致命。比较典的例子就是 Source Han Serif VF。

![图片](https://github.com/KonghaYao/cn-font-split/assets/41335471/0eb5856a-5f08-4ae6-a795-8ba8189ea9ed) and ![图片](https://github.com/KonghaYao/cn-font-split/assets/41335471/a6533caa-bcc5-4f53-95f0-f14b9891b7a1)

目前临时解决方案是在生成的 css 之后手动删除 font-weight。不清楚设置为 unset 会怎么样，但是这样有些似乎有些浪费了。

不过在 Variable Font 本身的字形切分上没有什么问题。（OTF 格式会报错，TTF 不会）

**Comment by KonghaYao** [comment]
感谢您的反馈，第一个需求是显式取消font-weight，第二个可能涉及到otp字体处理缺陷，请提供一份字体链接和cn-font-split，我们可以复现处理。

**Comment by immccn123** [comment]
字体链接是在 https://github.com/adobe-fonts/source-han-serif/raw/release/Variable/OTF/SourceHanSerifSC-VF.otf

cn-font-split 是 npm 上的命令行版本

**Comment by KonghaYao** [comment]
1. 完成 font-weight 显式不采用；--css.font-weight=false 即可
2. 完成大字体文件下的报错打断打包问题
3. 完成可变字体的字重测试，测试通过

我们通常会在周日进行版本发布，届时将会完成此 issue，感谢您的反馈😊。

**Comment by KonghaYao** [comment]
4.10.5 版本已经发布
