### ISSUE TITLE
在线分包出现以下报错

### ISSUE THREAD

**Issue by Lemonreds** [KonghaYao/cn-font-split#35]
<img width="1061" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/23014238/5bd229c6-8b85-4fb5-845d-1b67b67e1948">
使用在线分包出现以下报错：
Cannot read properties of undefined (reading 'glyphIndexMap')
请问是什么原因呢？

**Comment by Lemonreds** [comment]
请问是否是字体文件的问题呢？ woff2格式的

**Comment by KonghaYao** [comment]
cn-font-split 默认没有对 woff2 进行转换，所以会报错，你可以使用 otf 或者 ttf 版本的字体哦。线上版本将会在这周上线对 woff2 和 woff 字体的解析哈 😘

<img width="1064" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/3edbac72-2814-4914-ba7d-f229adf3f062">

**Comment by KonghaYao** [comment]
我回去看了看代码， cn-font-split 对 woff2 字体进行了解析，但是这个包内的 woff2 转换成为 ttf 格式时发生了一些变化，导致了程序阻断

**Comment by KonghaYao** [comment]
BUG 认定为这个包的 woff2 使用了非常特殊的操作，使得其不能被转化为 ttf 字体类型，后续操作都无法继续使用。对于此种字体的解决方式暂无，但是鉴于字体一般都会提供 otf 和 ttf，这个 BUG 暂时无法修复。

**Comment by KonghaYao** [comment]
@Lemonreds 此 BUG 已在 4.10.6 修复，感谢您的反馈哦 😊
