### ISSUE TITLE
[feature request] 支持 VariableFont

### ISSUE THREAD

**Issue by FairyScript** [KonghaYao/cn-font-split#36]
是否有考虑支持可变轴的 woff2 切片

> https://github.com/google/woff2

> https://henry.codes/writing/how-to-convert-variable-ttf-font-files-to-woff2/

**Comment by KonghaYao** [comment]
我记得可变字重是支持的通过了测试，我们也是使用的 woff2 wasm 版本进行压缩，应该是没有问题的

**Comment by FairyScript** [comment]
我用来测试的字体文件是 `NotoSansSC-VariableFont_wght.ttf`, 浏览器是 `Microsoft Edge 版本 120.0.2210.77 (正式版本) (64 位)`
在直接使用 `woff2_compress.exe` 压缩的情况下,可变字重正常,但使用 `cn-font-split` 切片的字体看起来只有 `thin` `regular` 和 `bold`三种情况. 而且我怀疑这三种是由浏览器控制的加粗而非预期中的可变字重

**Comment by KonghaYao** [comment]
<img width="2263" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/6f718f41-597b-49cd-b5f3-5e5ff817db51">

你是通过这种方式设置字重吗

```css
font-variation-settings: "wght" 900;
```

**Comment by FairyScript** [comment]
我创建了一个环境用于演示效果

https://codesandbox.io/p/devbox/font-split-demo-nrnr2p?embed=1&file=%2Fsrc%2FApp.tsx

![image](https://github.com/KonghaYao/cn-font-split/assets/7751581/d48d612f-5db0-47df-b695-6197eb129482)

**Comment by KonghaYao** [comment]
![image](https://github.com/KonghaYao/cn-font-split/assets/68177907/25b59407-213e-450d-ae0a-594bec063383)

codesanbox 对 css 中的 import 不太友好，没有加载到，你换成 js 中加载就 ok

**Comment by FairyScript** [comment]
原来如此,这看起来像是 vite 的问题

题外话,在编译生成的 `result.css` 文件当中删除 `font-weight` 属性之后,分割的字体也可以响应 `font-weight` 了,在当前的配置当中能做到在配置中设置不生成该属性么

**Comment by KonghaYao** [comment]
![image](https://github.com/KonghaYao/cn-font-split/assets/68177907/82c5bd4c-f782-436e-8f60-7e39eaea8845)
可以试试在配置项里面加上这个

**Comment by FairyScript** [comment]
完美的解决了问题,感谢
