### ISSUE TITLE
大佬 可以支持取字集的功能吗

### ISSUE THREAD

**Issue by zhang65681109** [KonghaYao/cn-font-split#38]
大佬可以添加怎么一个功能吗 输入部分文本 生成一个字体文件 文件里只有输入文本的字形

**Comment by richex-cn** [comment]
可以试试结合 [fontmin](https://github.com/ecomfe/fontmin) 使用。

如果需要的字符不多其实不用切，这个项目默认的单个分包 70K 能包含的字体已经不少了，所以只切一个包没太大意义。

**Comment by KonghaYao** [comment]
https://github.com/KonghaYao/cn-font-split/blob/325d4cdfd8dd0ef1a95f06c5adafc4136f3031af/packages/test/script/build.mjs#L24-L49

cn-font-split 支持自定义的字符级分包，名称为强制分包。
在 subsets 位置中可以填入数组，每个元素是单个的成品包；成品包是一个数组, 每个元素是 unicode 数字。这样子就可以任意分多少个包（注意把  autoChunk: false 加上，这样就只生成强制分包的内容；true的时候，会先分完你的包，然后再分剩下的包）。

@zhang65681109  希望能帮到你 😀
