### ISSUE TITLE
Emoji字体分包

### ISSUE THREAD

**Issue by ZERO-LJC** [KonghaYao/cn-font-split#41]
我尝试使用对Emoji字体进行分包

>  fontSplit({
>     FontPath: './NotoColorEmoji-Regular.ttf', 
>     destFold: './build',
>     chunkSize: 70 * 1024,
>     testHTML: true, 
>     reporter: true, 
>     previewImage: {}, 
>     threads: {}, 
>     targetType: 'ttf',
>     css: {},
>     renameOutputFont: '[hash:10][ext]',
> });

但是切割出来的字体大小远小于70kb，预览的时候也无法看到对应的emoji，是我使用方式的问题吗，还是不支持分割emoji

**Comment by KonghaYao** [comment]
<img width="713" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/e43c09e5-e010-46bd-9da6-69d1e1f0ee2f">

构建打包应该没有问题，问题出在对字体的解析上了，估计是部分 emoji 引用了特殊的 feature 导致分包失效了，猜测是 liga，不过我们在持续观察中。预览的 html 文件需要开个服务器才能看到，估计你是直接打开了

<img width="2558" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/b9717e85-9d89-4f8b-bc19-47ce44683f34">

**Comment by KonghaYao** [comment]
<img width="1150" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/65317b73-ff40-42dc-a69d-787a8169c75e">
这是我直接导入这个包的渲染情况，感觉这个包的特性浏览器没有完全实现好

**Comment by KonghaYao** [comment]
我研究了一下，原来 emoji 在 unicode 中是多个 数值合一的，所以需要一些特殊手段查看
<img width="1657" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/5a92cbfd-a7e8-430f-a42a-12e26330127a">

**Comment by KonghaYao** [comment]
唔，我这边用 cn-font-split 也进行分包测试了一下，渲染效果好像没有什么变化，过几天我写一个视觉测试全面测试一下。
然后，针对于分包 6 MB 过大的情况，看来需要特殊处理一下

**Comment by KonghaYao** [comment]
<img width="576" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/91c502d9-9a35-42fd-87eb-cb0260eefe54">
我对这个 emoji 字体做了一些视觉测试，发现 cn-font-split 的切割是正确的。现在就剩下切割的字符大小的问题了。

**Comment by KonghaYao** [comment]
唔，cn-font-split 版本号是多少 4.11.1 是最新版本，是没有问题的，我的 mac 上没有问题，linux 上可能会有偏差，请给个详细的环境呗

**Comment by ZERO-LJC** [comment]
我也是4.11.1 
<img width="457" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/9d681af2-07ee-43d8-ab4b-400c59921063">
intel 版本mac
<img width="250" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/f5b346ba-3ed2-4d48-b090-2a88838fc923">

**Comment by KonghaYao** [comment]
node 16 可能会有问题哦，cn-font-split 对 18 一下的版本支持不太好，你可以尝试一下 Github CodeSpace 里面直接试试， 一般 Github CodeSpace 上是能跑的

**Comment by ZERO-LJC** [comment]
<img width="845" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/886b3c60-4640-462b-9b9b-a3a93d391c35">
<img width="488" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/a34464f9-0e2d-4c20-9c86-38185eaef1b6">
很神奇

**Comment by KonghaYao** [comment]
<img width="969" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/4b2095f0-7ef1-4611-a8a4-824d3046adf9">
唔，我线上的 linux 跑的结果也和我本地的差不多，但是你这个确实离谱了。不过你的字体为啥是 24 MB 了呢，我在 noto color emoji 的仓库拿到的是 10 mb 的

**Comment by ZERO-LJC** [comment]
<img width="1101" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/9ae177a9-7442-477d-a26d-6f43b87ec795">
感谢回复~，我本来尝试使用在线分包，但显示这个，不知道是不是bug

**Comment by KonghaYao** [comment]
看了一下 google 自己线上的实现，感觉 emoji 绑在字体上不太实际，它太多太大了。opentype feature 贼多，导致单包很大，连 google 自己切出来的也是 700kb。因为 emoji 里面很多的换皮肤颜色的代码使得它不好弄，估计最终实现效果还没懒加载的 SVG 强。
<img width="1171" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/ad8b8e0e-2d1d-4bda-91aa-712dd012a62b">

**Comment by KonghaYao** [comment]
https://chinese-font.netlify.app/online-split/
试试这个，那个链接错了

**Comment by KonghaYao** [comment]
在线版本看起来也没毛病，不会是 intel 内核的问题吧 😂
<img width="785" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/4bc2f302-bafa-4e34-a6e9-ed8abf08983c">

**Comment by ZERO-LJC** [comment]
https://fonts.google.com/noto/specimen/Noto+Color+Emoji，我用的是这个24MB

**Comment by KonghaYao** [comment]
<img width="1528" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/33d3b85c-4f7c-443b-8715-d3b78bb9a302">
这个包切割的大小就和 google 差不多了，没有我的那个那么大

**Comment by ZERO-LJC** [comment]
是的，我刚刚跑完在线分包，这个包切到最后就只有2.17MB了，这是不是不合理
<img width="279" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/86391721/5915760a-9d1c-4ae1-8ae4-712e9a658634">

**Comment by KonghaYao** [comment]
这个我也不清楚，但是 我看google 线上的加起来也就 几 MB，估计这个24 MB 是设计版，没有压缩过。另外，我用的是 https://github.com/googlefonts/noto-emoji

**Comment by KonghaYao** [comment]
https://github.com/googlefonts/emoji-metadata 这里有 emoji 的源数据，里面有触发的 unicode

**Comment by KonghaYao** [comment]
6, Google 有个 COLRv1 的字体，可以减小到 4 MB 左右。
<img width="762" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/bcaaf448-b92f-4558-b1e2-77d39355109d">

**Comment by KonghaYao** [comment]
可惜兼容性不咋地
<img width="1608" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/1e935bff-03a3-43f5-922f-2b548a249fce">
