### ISSUE TITLE
添加对 Webpack / Vite 的支持

### ISSUE THREAD

**Issue by PrinOrange** [KonghaYao/cn-font-split#51]
有没有想过把这个库集成到 Webpack 和 Vite 中做成插件，允许构建时处理前端项目中的字体文件 🤔
[类似于 Next.js 中对本地字体的优化](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts)

**Comment by KonghaYao** [comment]
1. 如果用到了 cn-font-split，一般都是持久化字体包到 CDN 上了，通过主项目直接链接 CSS 文件。
2. 构建中处理的话，每次构建都要执行字体切割，像是在服务端持续集成就会比较吃力，单轮如果要跑测试的话，时间会更久。不如字体构建一次放置到 CDN 中，多个项目也可以同时使用。所以没有加入构建框架的插件。
3. 但是实现是可以的，通过解析源代码获取入口文件路径，塞进 cn-font-split 即可输出 css 文件地址，插入到 html 中即可。

**Comment by KonghaYao** [comment]
https://www.npmjs.com/package/vite-plugin-font
https://github.com/KonghaYao/cn-font-split/blob/ts/packages/vite/README_zh.md
vite-plugin-font 已经开发完毕了，但是我还没有进行实战测试嘞，估计晚些时候，在其他的项目里面会试试。 @PrinOrange
