### ISSUE TITLE
Error: -i or -o must be filled!

### ISSUE THREAD

**Issue by lizy0329-biubiubiu** [KonghaYao/cn-font-split#57]
![image](https://github.com/KonghaYao/cn-font-split/assets/103976180/37a01c35-f10f-4b5b-af07-d1588876736f)

本地分包：不可
线上分包：可

System：windows 10
终端：powershell

**Comment by KonghaYao** [comment]
尝试 使用  CMD 命令行试试，这个我晚点进行一波复现

**Comment by KonghaYao** [comment]
确认了 Powershell 的处理方式不一样，推荐使用 CMD 代码就没事了

**Comment by KonghaYao** [comment]
确认了 Powershell 的处理方式不一样，推荐使用 CMD 代码就没事了

**Comment by lizy0329-biubiubiu** [comment]
那这个 powershell 还有解决的希望吗？

**Comment by KonghaYao** [comment]
应该是有的，可能要等个版本更新一下读取的脚本，以前是直接文本解析的，可能 ps 解析有点问题

**Comment by KonghaYao** [comment]
@lizy0329-biubiubiu  4.14.0 修复
