### ISSUE TITLE
【在线分包】font-fmaily 不正确

### ISSUE THREAD

**Issue by lizy0329-biubiubiu** [KonghaYao/cn-font-split#58]
在线分包丢入 [阿里巴巴普惠体](https://www.alibabafonts.com/#/font)

![image](https://github.com/KonghaYao/cn-font-split/assets/103976180/d2cb935d-de1a-47f2-be7e-ddd48de42323)

其产物：
- 相同的 fontFamily
- 不同的 fontSubfamily

期望：
- 不同的 fontFamily
- 不同的 fontSubfamily

![image](https://github.com/KonghaYao/cn-font-split/assets/103976180/16e6812b-faa4-42b1-9d16-9ca6b4e93101)

**Comment by KonghaYao** [comment]
这两种分包产物的 weight 应该不是一致。因为可以同一个 font-family，不同 weight 匹配到不同的字体的

**Comment by lizy0329-biubiubiu** [comment]
> 这两种分包产物的 weight 应该不是一致。因为可以同一个 font-family，不同 weight 匹配到不同的字体的

在线分割后，他们的产物 weight 都是 400

**Comment by KonghaYao** [comment]
ok, 那这个会晚点修复，修复方式为不同的 weight

**Comment by KonghaYao** [comment]
4.14.0 版本已经修复此问题
