### ISSUE TITLE
window环境下，nextjs使用vite-plugin-font会解析路径失败

### ISSUE THREAD

**Issue by ShawDuChen** [KonghaYao/cn-font-split#63]
<img width="720" alt="Snipaste_2024-06-06_17-36-08" src="https://github.com/KonghaYao/cn-font-split/assets/39039604/b92ca252-bcb2-48e5-9f8c-61a23fc87d74">
原因应该是路径符号的问题
<img width="680" alt="Snipaste_2024-06-06_17-39-13" src="https://github.com/KonghaYao/cn-font-split/assets/39039604/b3766933-17f0-419e-9b03-96df941aaa8e">

**Comment by KonghaYao** [comment]
抽象了，不支持绝对路径。。。。

**Comment by ShawDuChen** [comment]
> 抽象了，不支持绝对路径。。。。

我这边尝试的解决方案是，使用url.fileURLToPath()来转换URL格式的文件路径，改成这样可以正确解析（不过仅对windows，其他环境还不确定）
<img width="644" alt="Snipaste_2024-06-06_17-45-11" src="https://github.com/KonghaYao/cn-font-split/assets/39039604/08c44307-da33-4cb3-b6d3-1be603429d02">

**Comment by KonghaYao** [comment]
@ShawDuChen  1.0.2 版本修复了 Windows 的路径问题，MacOS 上通过了测试，这个路径是可以的
