### ISSUE TITLE
全角括号的样式问题

### ISSUE THREAD

**Issue by i18n-now** [KonghaYao/cn-font-split#68]
（当原文此段未曾修改时）。

这句话

用阿里妈妈方圆体显示
https://www.iconfont.cn/fonts/detail?cnid=pOvFIr086ADR
<img width="1214" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/145643935/db58cfe1-7580-4c7a-9212-10166ae4d8c5">

用 https://github.com/KonghaYao/cn-font-split/issues/new 切分后显示
<img width="777" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/145643935/f8013a7a-7633-4da7-bf6b-fabc1638c2b6">

css https://registry.npmmirror.com/fc3/0.1.2/files/index.css
切分代码 https://github.com/i18n-site/font/blob/main/gen.coffee
字体文件 https://github.com/i18n-site/font/blob/main/otf/AlimamaFangYuanTiVF-Thin.ttf

改为英文括号后，曾的间距貌似也有问题
<img width="836" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/145643935/8240459d-8f46-4109-b79d-bd6c4a27aab9">

稍后将推出详细的教程。推的间距貌似也不对
<img width="895" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/145643935/1be67bab-e326-4847-874f-10d7ccf24f52">

**Comment by KonghaYao** [comment]
![image](https://github.com/KonghaYao/cn-font-split/assets/68177907/5cb1bd26-8078-4c4a-af7c-6768010c3fc3)

我猜测你的代码在处理  css 的时候，导致部分分包没有加载到，请查看浏览器的 console warning 面板，截个图查看一下哈 @i18n-now

**Comment by i18n-now** [comment]
对不起，我搞错了，是这个字体
这是拆分之前，直接引用ttf
[sinter.zip](https://github.com/user-attachments/files/15803606/sinter.zip)

这个是拆分后，打开 test.html

<img width="861" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/145643935/793e3963-af62-4266-be72-5094ff3b4d04">

[500.zip](https://github.com/user-attachments/files/15803595/500.zip)

**Comment by KonghaYao** [comment]
<img width="971" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/a50622f4-3668-476b-9824-03cf560c076e">

该字体源文件不符合 ttf 规范，`format('ttf')` 直接就加载不出来，当我在 CSS format 中不指定 ttf ，css 就可以加载出文件，而且BUG一模一样

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <style type="text/css">
    @font-face {
      font-family: "simple";
      src: url("./Sinter-Medium.ttf");
      font-style: normal;
      font-weight: 500;
      font-display: swap;
    }

    body {
      font-family: "simple";
      font-weight: 500;
      font-size: 20px;
    }
  </style>
</head>

<body>
  （当原文此段未曾修改时）。
</body>

</html>
```

**Comment by i18n-now** [comment]
哦，明白，我换个字体吧
