### ISSUE TITLE
能支持从多个字体导出吗？MiSans Global 的可变宽字体是很多个文件

### ISSUE THREAD

**Issue by i18n-now** [KonghaYao/cn-font-split#70]
MiSans Global 的可变宽字体是很多个文件，没有一个全集文件 
https://hyperos.mi.com/font/zh/download/

MiSans_Devanagari_VF.ttf  MiSans_Gurmukhi_VF.ttf  MiSans_Myanmar_VF.ttf  MiSans_VF.ttf       MiSansKhmerVF.ttf  MiSansThaiVF.ttf MiSans_Gujarati_VF.ttf    MiSans_Latin_VF.ttf     Misans_TC_VF.ttf       MiSansArabicVF.ttf  MiSansLaoVF.ttf    MiSansTibetanVF.ttf

我本来打算合并一下再用 cn-font-split

但是发现没法用fonttools合并可变宽 https://github.com/fonttools/fonttools/issues/1059

我也没研究出没其他合并可变宽字体的方案

有没有一个办法从多个文件导出，感觉这样可能会更容易

这里可以在线预览可变字重
https://hyperos.mi.com/font/zh/details/sc/

**Comment by KonghaYao** [comment]
其实你可以单独对每个字体进行分割，然后获取到不同的 result.css,根据你的网页的具体内容选择使用的分包，不需要完整的一个字体文件。如果你直接使用多个 css 文件，虽然css 多一点，浏览器也是会按需加载的

**Comment by i18n-now** [comment]
明白，我想想怎么弄

**Comment by i18n-now** [comment]
我找到方案了，用subsets
https://github.com/KonghaYao/cn-font-split/issues/38#issuecomment-1871859244
