### ISSUE TITLE
Variable-Font 字体分包的问题：VF字体被分包后字重丢失。

### ISSUE THREAD

**Issue by codemetic** [KonghaYao/cn-font-split#72]
一般来说，[多字重字体，也被称为VF字体](https://www.hozen.site/archives/64/#%E5%8F%AF%E5%8F%98%E5%AD%97%E4%BD%93variable-font)，可以在一个TTF文件中集成 `Extra Light,Light,Regular,Bold,SemiBold` 等多个字重。
但是 `cn-font-split` 对这类 VF 字体分包后，只有 `Extra Light` 这一个字重，其他字重全部丢失。

例如这个 `NotoSerifKR` 字体，[这是下载地址](https://github.com/user-attachments/files/16051717/noto-serif-kr.zip)

它有多个字重，点击“下一页”可以预览多个字重。

![image](https://github.com/KonghaYao/cn-font-split/assets/163226980/804917e2-492d-49bd-aee2-3772c62cb784)

在执行命令

```bash
cn-font-split -i=./noto-serif-kr.ttf -o ./
```
对字体分包后，只剩下`Extra Light`这一个字重，其他字重全部丢失。
![image](https://github.com/KonghaYao/cn-font-split/assets/163226980/98822fe1-2f26-4043-ac49-d65be66608ff)

所以我想：能否对VF字体分包后，不要丢失其他字重？

**非常感谢！**

**Comment by KonghaYao** [comment]
<img width="1876" alt="image" src="https://github.com/KonghaYao/cn-font-split/assets/68177907/123b689e-91ce-4eef-88ca-85844c0b9426">
cn-font-split 并没有丢失字重，而是 css 的设置方式问题，请使用这个 css 变量更改所选区域的字重大小

**Comment by KonghaYao** [comment]
@codemetic 新 4.6.0 版本支持 css 中 font-weight 直接改变字重，您可以重新尝试一下，感谢您的反馈
