### ISSUE TITLE
Firefox提示maxZone:0

### ISSUE THREAD

**Issue by KanbeKotoriDaisuki** [KonghaYao/cn-font-split#74]
现行css模板在firefox下会提示`downloadable font: maxp: Bad maxZones: 0`。参见https://github.com/ecomfe/fontmin/issues/83#issuecomment-1143771799。

去除https://github.com/KonghaYao/cn-font-split/blob/911b85d6ec11fb515cc6715eae2f80f35f4dfaa2/packages/subsets/src/templates/css.ts#L75 中间的空格应当即可解决。

**Comment by KonghaYao** [comment]
您好，感谢您的提示。这个 issue 需要有具体的字体及环境复现，可以的话，请提供一下哈 @KanbeKotoriDaisuki

**Comment by KanbeKotoriDaisuki** [comment]
字体：[资源圆体TTC全字符](https://github.com/CyanoHao/Resource-Han-Rounded/releases/tag/v0.990)
环境：vite插件下
```javascript
{
  renameOutputFont: "[hash][ext]",
  chunkSize: 1000 * 1024,
  chunkSizeTolerance: 1.5,
  testHTML: true,
}
```

**Comment by KanbeKotoriDaisuki** [comment]
> 字体：[资源圆体TTC全字符](https://github.com/CyanoHao/Resource-Han-Rounded/releases/tag/v0.990) 环境：vite插件下
> 
> ```js
> {
>   renameOutputFont: "[hash][ext]",
>   chunkSize: 1000 * 1024,
>   chunkSizeTolerance: 1.5,
>   testHTML: true,
> }
> ```

不过开不开输出样例html文件是一样的就是了

**Comment by KanbeKotoriDaisuki** [comment]
我实际使用的是cn版本各个字重的ttf，上面打错了。我测试用的环境是firefox 128.0，不排除是更新把老bug又刷出来了。

**Comment by KonghaYao** [comment]
感谢 5.1.1 版本修复了在 firefox 的这个 BUG！@KanbeKotoriDaisuki
