### ISSUE TITLE
字体CDN链接404

### ISSUE THREAD

**Issue by zweifisch** [KonghaYao/cn-font-split#77]
部分加载成功，应该是本地缓存

![protoboard-36akfd](https://github.com/user-attachments/assets/aac38f2d-00da-4e4d-aa57-457bc0e3e388)

直接用的这个链接
https://chinese-fonts-cdn.deno.dev/packages/rzjkxzdmh/dist/nzgrKangxi/result.css

<img width="940" alt="image" src="https://github.com/user-attachments/assets/a2f3bdee-975a-4793-a99f-c495dab8a052">

**Comment by KonghaYao** [comment]
可否发送一下 result.css 的头部信息以确认版本。因为 字图 CDN 有 redirect 缓存和 result.css 的缓存，是根据不同版本进行的缓存。@zweifisch
<img width="797" alt="image" src="https://github.com/user-attachments/assets/3eed85e0-bb99-4ff0-9517-e5523fc99b35">
