### ISSUE TITLE
vite-plugin-font插件在开发环境下不能生成cache

### ISSUE THREAD

**Issue by jktantan** [KonghaYao/cn-font-split#85]
在开发环境下使用vite-plugin-font的插件，它不能直接生成字体的cache,必须要先Build一次才行

**Comment by KonghaYao** [comment]
是不是     最小化构建不支持热更新？还是全量构建 cache 失效？

**Comment by KonghaYao** [comment]
还有你使用的框架是 vite 还是 nuxt 还是 nest

**Comment by jktantan** [comment]
> 是不是 最小化构建不支持热更新？还是全量构建 cache 失效？

全量和最小都不行，都需要BUILD一次才有。
我用的是NUXT的框架。

**Comment by KonghaYao** [comment]
这边已经复现 nuxt 3 版本 client 不构建的问题了，现在可以改为使用 vite 插件的模式进行构建而不使用 module。 vite 的构建应该是可以的 @jktantan 

```js
// https://nuxt.com/docs/api/configuration/nuxt-config
import font from 'vite-plugin-font'
export default defineNuxtConfig({
  devtools: { enabled: false },
  // modules: ["module/nuxt"],
  vite:{
    plugins:[
      font.vite({})
    ]
  },
  compatibilityDate: "2024-10-26",
});
```

**Comment by jktantan** [comment]
> 这边已经复现 nuxt 3 版本 client 不构建的问题了，现在可以改为使用 vite 插件的模式进行构建而不使用 module。 vite 的构建应该是可以的 @jktantan
> 
> ```js
> // https://nuxt.com/docs/api/configuration/nuxt-config
> import font from 'vite-plugin-font'
> export default defineNuxtConfig({
>   devtools: { enabled: false },
>   // modules: ["module/nuxt"],
>   vite:{
>     plugins:[
>       font.vite({})
>     ]
>   },
>   compatibilityDate: "2024-10-26",
> });
> ```

试了一下，使用vite的方式没有问题。

**Comment by KonghaYao** [comment]
3.0.0 版本以后将统一使用 vite 方式，以前的 nuxt 插件将会被废弃
