### ISSUE TITLE
分包策略优化

### ISSUE THREAD

**Issue by Yubiao-Li** [KonghaYao/cn-font-split#9]
这里目前是按unicode顺序做的分包，是否有考虑过按照字符使用频率做分包呢，这样或许能否拉尽可能少的分包就可以完成渲染

**Comment by KonghaYao** [comment]
这几行代码 使用了中文字符使用频率的算法数据集
https://github.com/KonghaYao/cn-font-split/blob/c53d0c6ef018f4e9910e99fbbb280345ead4a391/packages/subsets/src/main.ts#L138-L142

**Comment by Yubiao-Li** [comment]
> 这几行代码 使用了中文字符使用频率的算法数据集
> 
> https://github.com/KonghaYao/cn-font-split/blob/c53d0c6ef018f4e9910e99fbbb280345ead4a391/packages/subsets/src/main.ts#L138-L142

https://chinese-font.netlify.app/online-split/也就是目前通过这个网站得到的分包已经应用了这个策略吗

**Comment by KonghaYao** [comment]
对的，这个页面内部是最新版本的 cn-font-split, 使用你的浏览器进行分包，也是用了这个策略的。
中文使用率排序是 3 版本就已经应用的特性，往后的字体都是经过这个排序优化的

**Comment by KonghaYao** [comment]
对的，这个页面内部是最新版本的 cn-font-split, 使用你的浏览器进行分包，也是用了这个策略的。
中文使用率排序是 3 版本就已经应用的特性，往后的字体都是经过这个排序优化的
