### ISSUE TITLE
在 Nuxt 中 怎么使用 vite-plugin-font 来进行多个字体载入 

### ISSUE THREAD

**Issue by Xiangzi529** [KonghaYao/cn-font-split#92]
因为有多语言 然后有多个字体包 看文档没看明白 import { css, fontFamilyFallback } from '../demo/public/SmileySans-Oblique.ttf';
document.body.style.fontFamily = `"${css.family}", ` + fontFamilyFallback; 我有多个这个逻辑应该写在哪里

**Comment by KonghaYao** [comment]
多个字体载入可以这样使用 @Xiangzi529
```js
const fontConfig = {
    a: ()=>  import('../demo/public/SmileySans-Oblique.ttf')
    // 这里注册多个字体
}
/* 传入字体名称，载入 */
const loadFont = async (name)=>{
    const { css, fontFamilyFallback } = await fontConfig[name]()
    // 就是把 font-family 设置为这个字符串，你可以随意挂载到 什么 dom 上
    document.body.style.fontFamily = "${css.family}",  + fontFamilyFallback; 
}
```

**Comment by Xiangzi529** [comment]
> 多个字体载入可以这样使用 @Xiangzi529
> 
> ```js
> const fontConfig = {
>     a: ()=>  import('../demo/public/SmileySans-Oblique.ttf')
>     // 这里注册多个字体
> }
> /* 传入字体名称，载入 */
> const loadFont = async (name)=>{
>     const { css, fontFamilyFallback } = await fontConfig[name]()
>     // 就是把 font-family 设置为这个字符串，你可以随意挂载到 什么 dom 上
>     document.body.style.fontFamily = "${css.family}",  + fontFamilyFallback; 
> }
> ```

好吧 我后面直接分包 丢cdn了 有些东西是后端返的 单纯打包好像还不太行 不是很会用
